#pragma once

//#define USE_MATRIX_I2C


/* Select hand configuration */
#define EE_HANDS

#define LAYER_STATE_8BIT

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#define TAPPING_FORCE_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 100
#define PERMISSIVE_HOLD
#define NO_ACTION_ONESHOT
#define USB_POLLING_INTERVAL_MS 1

#define FORCE_NKRO
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define TRI_LAYER_LOWER_LAYER 2
#define TRI_LAYER_UPPER_LAYER 3
#define TRI_LAYER_ADJUST_LAYER 4

#define MOUSEKEY_INTERVAL           10
#define MOUSEKEY_DELAY              0
#define MOUSEKEY_TIME_TO_MAX        120
#define MOUSEKEY_MAX_SPEED          3
#define MOUSEKEY_WHEEL_DELAY        400
#define MOUSEKEY_WHEEL_INTERVAL     40
#define MOUSEKEY_WHEEL_MAX_SPEED    7
#define MOUSEKEY_WHEEL_TIME_TO_MAX  60

#define OLED_TIMEOUT 60000
#define OLED_BRIGHTNESS 255
#define OLED_UPDATE_INTERVAL 250

#if defined(KEYBOARD_sofle_sophie)
#    define OLED_DISPLAY_128X64
#endif

#ifdef RGBLIGHT_ENABLE

#define WS2812_DI_PIN D3

#define RGBLIGHT_SLEEP

#undef RGBLED_NUM
#if defined(KEYBOARD_sofle_rev1)
#    define RGBLED_NUM 72
#elif defined(KEYBOARD_sofle_sophie)
#    define RGBLED_NUM 16
#endif
#undef RGBLED_SPLIT

#define RGBLED_SPLIT { RGBLED_NUM/2, RGBLED_NUM/2 }

#define RGBLIGHT_LIMIT_VAL 255
#define RGBLIGHT_HUE_STEP 2
#define RGBLIGHT_SAT_STEP 5
#define RGBLIGHT_VAL_STEP 5

#define RGBLIGHT_DEFAULT_HUE 130

#define RGBLIGHT_EFFECT_STATIC_LIGHT
#endif
