#pragma once

//#define USE_MATRIX_I2C


/* Select hand configuration */

#define MASTER_LEFT
// #define MASTER_RIGHT
//#define EE_HANDS
//#define USE_SERIAL_PD2
//#define USE_MATRIX_I2C

#define LAYER_STATE_8BIT

#undef ENCODER_RESOLUTION 
#define ENCODER_RESOLUTION 4

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 100

/* ws2812 RGB LED */
#define RGB_DI_PIN D3

#define OLED_TIMEOUT 60000
#define OLED_BRIGHTNESS 200
#define OLED_UPDATE_INTERVAL 1000

#define WPM_LAUNCH_CONTROL
#define WPM_SAMPLE_SECONDS 5
#define WPM_SAMPLE_PERIODS 25

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_SPLIT
#define RGBLED_NUM 72
#define RGBLED_SPLIT { 36, 36 }
//#define DRIVER_LED_TOTAL 72
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_LIMIT_VAL 255
#define RGBLIGHT_HUE_STEP 2
#define RGBLIGHT_SAT_STEP 5
#define RGBLIGHT_VAL_STEP 5


//#define RGBLIGHT_EFFECT_STATIC_LIGHT
//#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
#endif
